server:
  port: 9003
  servlet:
    context-path: /file # 以/file访问该服务

# spring配置
spring:
  application:
    name: file-client

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: file-9003 # 重点，和client平级
    prefer-ip-address: true # true访问路径可以显示IP地址

file:
  path: D:/file/imooc/course
  domain: http://127.0.0.1:9000/file/
