# mybatis配置
mybatis:
  type-aliases-package: com.company.server.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

# sql日志级别配置
logging:
  level:
    com.company.server.mapper: trace  # 设置com.company.system.mapper目录下的日志为trace级别，可显示sql详情

# spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/mooc # 数据库名称
    username: moocuser
    password: 123456
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间
  redis:
    host: localhost
    port: 6379
