server:
  port: 9000

#spring配置
spring:
  application:
    name: gateway-client

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: gateway-9000 # 重点，和client平级
    prefer-ip-address: true # true访问路径可以显示IP地址